In [1]:
import pandas as pd

# Load the Excel dataset
df = pd.read_excel("../data/raw/Data_Train.xlsx")

# Display the first 5 rows
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [2]:
# Shape of the dataset
print("Dataset Shape:", df.shape)

# Column names
print("\nColumn Names:")
print(df.columns)

# First 5 rows
print("\nFirst 5 Rows:")
display(df.head())

Dataset Shape: (10683, 11)

Column Names:
Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='str')

First 5 Rows:

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [3]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [4]:
# Missing values
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [5]:
# Statistical summary
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [6]:
print("Dataset Shape:", df.shape)
print("\nColumn Names:")
print(df.columns)

Dataset Shape: (10683, 11)

Column Names:
Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [8]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [9]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [10]:
# Check duplicate rows
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 220

In [11]:
# Remove duplicate rows
df = df.drop_duplicates()

print("New Dataset Shape:", df.shape)

New Dataset Shape: (10463, 11)

In [12]:
# Check missing values again
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [13]:
# Remove missing values
df = df.dropna()

print(df.shape)

(10462, 11)

In [14]:
# Check duplicate rows
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [15]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [16]:
df = df.dropna()

print("Final Dataset Shape:", df.shape)

Final Dataset Shape: (10462, 11)

In [17]:
# Convert Date_of_Journey to datetime
df["Date_of_Journey"] = pd.to_datetime(
    df["Date_of_Journey"],
    format="%d/%m/%Y"
)

# Create new features
df["Journey_Day"] = df["Date_of_Journey"].dt.day
df["Journey_Month"] = df["Date_of_Journey"].dt.month

# Check the result
df[["Date_of_Journey", "Journey_Day", "Journey_Month"]].head()

  Date_of_Journey  Journey_Day  Journey_Month
0      2019-03-24           24              3
1      2019-05-01            1              5
2      2019-06-09            9              6
3      2019-05-12           12              5
4      2019-03-01            1              3

In [18]:
# Convert Departure Time to datetime
df["Dep_Time"] = pd.to_datetime(df["Dep_Time"])

# Extract Departure Hour and Minute
df["Departure_Hour"] = df["Dep_Time"].dt.hour
df["Departure_Minute"] = df["Dep_Time"].dt.minute

# Display the result
df[["Dep_Time", "Departure_Hour", "Departure_Minute"]].head()

C:\Users\A.VARISHA FEMIN\AppData\Local\Temp\ipykernel_29536\939188246.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Dep_Time"] = pd.to_datetime(df["Dep_Time"])

             Dep_Time  Departure_Hour  Departure_Minute
0 2026-07-07 22:20:00              22                20
1 2026-07-07 05:50:00               5                50
2 2026-07-07 09:25:00               9                25
3 2026-07-07 18:05:00              18                 5
4 2026-07-07 16:50:00              16                50

In [19]:
# Extract only the time part from Arrival_Time
df["Arrival_Time"] = df["Arrival_Time"].str.split(" ").str[0]

# Convert to datetime
df["Arrival_Time"] = pd.to_datetime(df["Arrival_Time"])

# Extract Arrival Hour and Minute
df["Arrival_Hour"] = df["Arrival_Time"].dt.hour
df["Arrival_Minute"] = df["Arrival_Time"].dt.minute

# Display the result
df[["Arrival_Time", "Arrival_Hour", "Arrival_Minute"]].head()

C:\Users\A.VARISHA FEMIN\AppData\Local\Temp\ipykernel_29536\991847983.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Arrival_Time"] = pd.to_datetime(df["Arrival_Time"])

         Arrival_Time  Arrival_Hour  Arrival_Minute
0 2026-07-07 01:10:00             1              10
1 2026-07-07 13:15:00            13              15
2 2026-07-07 04:25:00             4              25
3 2026-07-07 23:30:00            23              30
4 2026-07-07 21:35:00            21              35

In [20]:
# Display some duration values
df["Duration"].head(10)

0     2h 50m
1     7h 25m
2        19h
3     5h 25m
4     4h 45m
5     2h 25m
6    15h 30m
7     21h 5m
8    25h 30m
9     7h 50m
Name: Duration, dtype: str

In [21]:
# Replace missing hours or minutes with 0
df["Duration"] = df["Duration"].str.replace("h", "h ")
df["Duration"] = df["Duration"].str.replace("m", "m ")

# Extract hours
df["Duration_Hours"] = (
    df["Duration"]
      .str.extract(r'(\d+)h')
      .fillna(0)
      .astype(int)
)

# Extract minutes
df["Duration_Minutes"] = (
    df["Duration"]
      .str.extract(r'(\d+)m')
      .fillna(0)
      .astype(int)
)

# Total duration in minutes
df["Duration_Total_Minutes"] = (
    df["Duration_Hours"] * 60
    + df["Duration_Minutes"]
)

# Display result
df[["Duration",
    "Duration_Hours",
    "Duration_Minutes",
    "Duration_Total_Minutes"]].head()

   Duration  Duration_Hours  Duration_Minutes  Duration_Total_Minutes
0  2h  50m                2                50                     170
1  7h  25m                7                25                     445
2      19h               19                 0                    1140
3  5h  25m                5                25                     325
4  4h  45m                4                45                     285

In [22]:
print(df["Total_Stops"].unique())

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', '4 stops']
Length: 5, dtype: str

In [23]:
# Convert Total_Stops into numerical values

df["Total_Stops"] = df["Total_Stops"].replace({
    "non-stop": 0,
    "1 stop": 1,
    "2 stops": 2,
    "3 stops": 3,
    "4 stops": 4
})

# Check the result
df[["Total_Stops"]].head()

  Total_Stops
0           0
1           2
2           2
3           1
4           1

In [24]:
df.dtypes

Airline                              str
Date_of_Journey           datetime64[us]
Source                               str
Destination                          str
Route                                str
Dep_Time                  datetime64[us]
Arrival_Time              datetime64[us]
Duration                             str
Total_Stops                       object
Additional_Info                      str
Price                              int64
Journey_Day                        int32
Journey_Month                      int32
Departure_Hour                     int32
Departure_Minute                   int32
Arrival_Hour                       int32
Arrival_Minute                     int32
Duration_Hours                     int64
Duration_Minutes                   int64
Duration_Total_Minutes             int64
dtype: object

In [25]:
print(df["Airline"].unique())

<StringArray>
[                           'IndiGo',                         'Air India',
                       'Jet Airways',                          'SpiceJet',
                 'Multiple carriers',                             'GoAir',
                           'Vistara',                          'Air Asia',
           'Vistara Premium economy',              'Jet Airways Business',
 'Multiple carriers Premium economy',                            'Trujet']
Length: 12, dtype: str

In [26]:
# One-Hot Encoding for Airline
airline = pd.get_dummies(df["Airline"], prefix="Airline", dtype=int)

# Display first few rows
airline.head()

,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,Airline_Vistara,Airline_Vistara Premium economy
0,0,0,0,1,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,0,0

In [27]:
source = pd.get_dummies(df["Source"], prefix="Source", dtype=int)

source.head()

,Source_Banglore,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai
0,1,0,0,0,0
1,0,0,0,1,0
2,0,0,1,0,0
3,0,0,0,1,0
4,1,0,0,0,0

In [28]:
destination = pd.get_dummies(df["Destination"], prefix="Destination", dtype=int)

destination.head()

,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,0,0,0,0,0,1
1,1,0,0,0,0,0
2,0,1,0,0,0,0
3,1,0,0,0,0,0
4,0,0,0,0,0,1

In [29]:
df = pd.concat(
    [df, airline, source, destination],
    axis=1
)

print(df.shape)

(10462, 43)

In [ ]:
venv/
__pycache__/
.ipynb_checkpoints/
*.pyc
.DS_Store